# Generated by Django 5.2.17 on 2026-09-19 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Follower-controlled pause.')),
                ('is_banned', models.BooleanField(default=False, help_text='Admin-controlled block.')),
                ('sizing_mode', models.CharField(choices=[('proportional', 'Proportional to equity (x scale)'), ('fixed_notional', 'Fixed USDT per trade'), ('multiplier', 'Multiple of master quantity')], default='proportional', max_length=20)),
                ('sizing_value', models.DecimalField(decimal_places=10, default=1, max_digits=28)),
                ('max_notional_per_trade', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('max_leverage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('allowed_symbols', models.TextField(blank=True, help_text='Comma-separated, e.g. BTC-USDT,ETH-USDT. Empty = all.')),
                ('blocked_symbols', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('symbol', models.CharField(max_length=32)),
                ('side', models.CharField(max_length=4)),
                ('position_side', models.CharField(max_length=5)),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('price', models.DecimalField(decimal_places=10, max_digits=28)),
                ('leverage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('position_qty_after', models.DecimalField(decimal_places=10, max_digits=28)),
                ('master_equity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('raw', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copying_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_enc', models.TextField()),
                ('api_secret_enc', models.TextField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='copier.follower')),
            ],
        ),
        migrations.CreateModel(
            name='CopyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_order_id', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filled', 'Filled'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('unknown', 'Unknown')], db_index=True, default='pending', max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True)),
                ('exchange_order_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='copier.follower')),
                ('master_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='copier.masterevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('master_event', 'follower'), name='one_copy_per_follower_event')],
            },
        ),
    ]
