# Generated by Django 5.2.17 on 2026-09-19 13:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='flatten_on_max_loss',
            field=models.BooleanField(default=False, help_text='Also close all positions when the daily loss limit trips.'),
        ),
        migrations.AddField(
            model_name='follower',
            name='guard_baseline_at',
            field=models.DateTimeField(blank=True, help_text='Drawdown is measured from this moment or 24h ago, whichever is later (reset on /resume).', null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='max_daily_loss_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='max_exposure_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('80'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='max_slippage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('1.00'), max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='follower',
            name='stop_loss_roi_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='GuardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_events', to='copier.follower')),
            ],
        ),
        migrations.CreateModel(
            name='EquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity', models.DecimalField(decimal_places=10, max_digits=28)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='copier.follower')),
            ],
            options={
                'indexes': [models.Index(fields=['follower', 'created_at'], name='copier_equi_followe_0e9df4_idx')],
            },
        ),
    ]
