# Generated by Django 5.2.17 on 2026-09-20 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copier', '0002_follower_flatten_on_max_loss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('beat_at', models.DateTimeField()),
                ('detail', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to='copier.follower')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('follower', 'version'), name='one_acceptance_per_version')],
            },
        ),
    ]
