# Generated by Django 5.2.17 on 2026-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copier', '0003_heartbeat_termsacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterevent',
            name='card_status',
            field=models.CharField(db_index=True, default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='masterevent',
            name='result_entry_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='masterevent',
            name='result_exit_price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='masterevent',
            name='result_leverage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='masterevent',
            name='result_qty',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=28, null=True),
        ),
    ]
